import { Product, Factory, Owner, ClientLocation } from './types';

export const PRODUCTS: Product[] = [
    {
        id: 'p1',
        name: 'Statuario Maximus',
        category: 'Marble',
        finish: 'Polished',
        dimensions: '3200 x 1600 mm',
        description: 'Premium white marble with bold grey veining, perfect for luxury interiors.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790512/1_lpd8a7.jpg',
        factoryId: 'f1',
        featured: true,
        color: 'White',
        applications: ['Countertops', 'Wall Panels', 'Flooring'],
        altText: 'Statuario Maximus polished white marble slab with grey veining',
    },
    {
        id: 'p2',
        name: 'Black Galaxy',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Iconic deep black granite with gold speckles, durable and elegant.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790197/3_b9h22f.jpg',
        factoryId: 'f2',
        featured: true,
        color: 'Black',
        applications: ['Countertops', 'Flooring', 'Cladding'],
        altText: 'Black Galaxy granite polished slab with gold mineral speckles',
    },
    {
        id: 'p3',
        name: 'Honey Onyx',
        category: 'Onyx',
        finish: 'Backlit',
        dimensions: '2400 x 1400 mm',
        description: 'Translucent stone with warm amber tones, ideal for statement features.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790197/4_nhlyg2.jpg',
        factoryId: 'f1',
        featured: false,
        color: 'Gold',
        applications: ['Decorative', 'Wall Panels', 'Feature Walls'],
        altText: 'Honey Onyx translucent backlit stone with warm amber tones',
    },
    {
        id: 'p4',
        name: 'Silver Travertine',
        category: 'Travertine',
        finish: 'Honed',
        dimensions: '2800 x 1600 mm',
        description: 'Contemporary silver-grey travertine with linear veining.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790198/5_tjbom0.jpg',
        factoryId: 'f3',
        featured: true,
        color: 'Grey',
        applications: ['Flooring', 'Cladding', 'Wall Panels'],
        altText: 'Silver Travertine honed stone with contemporary linear veining',
    },
    {
        id: 'p5',
        name: 'Colonial White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1900 mm',
        description: 'Soft white granite with speckles of black and dark red garnet.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790534/3_ryd77a.jpg',
        factoryId: 'f2',
        featured: false,
        color: 'White',
        applications: ['Countertops', 'Flooring', 'Cladding'],
        altText: 'Colonial White polished granite with black and red garnet speckles',
    },
    {
        id: 'p6',
        name: 'Viscon White',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '2900 x 1700 mm',
        description: 'A mesmerizing swirl of white, grey, and black waves.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790526/2_r5us0g.jpg',
        factoryId: 'f2',
        featured: true,
        color: 'White',
        applications: ['Countertops', 'Wall Panels', 'Decorative'],
        altText: 'Viscon White granite leather finish with swirling wave patterns',
    },
    {
        id: 'p7',
        name: 'Tan Brown',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Classic dark brown granite with black and reddish-brown flecks.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790535/4_r1z0ue.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p8',
        name: 'Absolute Black',
        category: 'Granite',
        finish: 'Honed',
        dimensions: '3200 x 1900 mm',
        description: 'The deepest, darkest black granite for a sleek modern look.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790536/5_lbu7fv.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p9',
        name: 'Rainforest Green',
        category: 'Marble',
        finish: 'Polished',
        dimensions: '2800 x 1500 mm',
        description: 'Exotic green marble with intricate brown branching veins.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790537/6_sa14fp.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p10',
        name: 'Steel Grey',
        category: 'Granite',
        finish: 'Lappato',
        dimensions: '3000 x 1800 mm',
        description: 'Consistent low-variation grey granite, ideal for large commercial projects.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790537/6_wkrtxe.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p11',
        name: 'Rajasthan Black',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '2900 x 1600 mm',
        description: 'Durable black granite with a textured finish for outdoor use.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790538/7_ffocgw.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p12',
        name: 'Kuppam Green',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2800 x 1700 mm',
        description: 'Vibrant green granite with flowing wavy patterns.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790540/8_xptiku.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p13',
        name: 'Imperial Red',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1800 mm',
        description: 'Deep red granite with blue-black accents, symbolizing royalty.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790541/9_axiqls.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p14',
        name: 'Crystal Yellow',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1700 mm',
        description: 'Bright and cheerful yellow granite with uniform consistency.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790513/10_wcagey.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p15',
        name: 'River White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Flowing rivers of white and light grey with red burgundy dots.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790514/11_zhnlph.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p16',
        name: 'Alaska White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3200 x 1900 mm',
        description: 'Frosty mix of pale silver and frosty whites, marketed as exotic.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790516/12_ruwjss.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p17',
        name: 'Blue Dunes',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '3100 x 1900 mm',
        description: 'Earth tones of varying cream, grey, and brown with unique blue hues.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790518/13_ibxzlp.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p18',
        name: 'Monte Cristo',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Dynamic granite featuring sweeping waves of blue and grey.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790520/14_tixvo4.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p19',
        name: 'P White',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '2800 x 1600 mm',
        description: 'Economical and durable white granite, perfect for large scale paving.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790521/15_lddg0j.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p20',
        name: 'Tiger Skin',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1700 mm',
        description: 'Orange and black wavy patterns resembling a tiger\'s coat.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790522/16_gcakzn.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p21',
        name: 'Rosy Pink',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1700 mm',
        description: 'Pastel pink base with white and black flowers.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790524/17_lpzglc.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p22',
        name: 'Apple Green',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2800 x 1700 mm',
        description: 'Olive green background with speckles of pink and grey.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790524/18_qu4cpa.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p23',
        name: 'Chima Pink',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '3100 x 1800 mm',
        description: 'Light pink granite widely used for flooring and cladding.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790525/19_z28kte.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p24',
        name: 'Markino Red',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1600 mm',
        description: 'Intense red background with bold black waves.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790527/20_aqpure.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p25',
        name: 'Cosmic Black',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1900 mm',
        description: 'Deep black granite with subtle silver undertones.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790538/7_uqmijv.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p26',
        name: 'Aurora White',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '3000 x 1700 mm',
        description: 'Luminous white with mystical grey veining patterns.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790526/2_qas8jq.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p27',
        name: 'Desert Gold',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1800 mm',
        description: 'Warm golden tones with brown and black mineral deposits.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790529/23_rpsqld.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p28',
        name: 'Ocean Blue',
        category: 'Granite',
        finish: 'Honed',
        dimensions: '3200 x 1600 mm',
        description: 'Deep blue granite with flowing white wave patterns.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790530/24_m1ydkz.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p29',
        name: 'Emerald Dreams',
        category: 'Marble',
        finish: 'Polished',
        dimensions: '2800 x 1700 mm',
        description: 'Rich emerald green with white crystalline patterns.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790530/25_ybemof.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p30',
        name: 'Sunset Bronze',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '3000 x 1900 mm',
        description: 'Warm bronze and copper tones for dramatic interiors.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790531/26_ircf5m.jpg',
        factoryId: 'f3',
        featured: true,
    },
    {
        id: 'p31',
        name: 'Midnight Silver',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1700 mm',
        description: 'Dark grey with silver mineral flecks for modern elegance.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790532/27_epajqg.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p32',
        name: 'Forest Green',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '2900 x 1600 mm',
        description: 'Deep forest green with black and white speckles.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790532/28_osawvk.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p33',
        name: 'Champagne Gold',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Elegant champagne gold with subtle pink undertones.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790533/29_seqv1o.jpg',
        factoryId: 'f3',
        featured: true,
    },
    {
        id: 'p34',
        name: 'Twilight Purple',
        category: 'Granite',
        finish: 'Honed',
        dimensions: '2800 x 1500 mm',
        description: 'Rare purple granite with grey and white streaks.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790535/30_iwtmhv.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p35',
        name: 'Tan Brown Vanity',
        category: 'Granite',
        finish: 'Polished',
        dimensions: 'Custom',
        description: 'Exquisite Tan Brown Granite applied in a luxury bathroom vanity setting.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1773075960/Tan_Brown_Granite_Bathroom_Vanity___Marble_com_lwooww.jpg',
        factoryId: 'f3',
        featured: true,
    },
    {
        id: 'p36',
        name: 'Tan Brown (Slab)',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Classic dark brown granite with black and reddish-brown flecks, showcasing an entire slab.',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1773075960/Tan_Brown_Granite_1_pt860k.jpg',
        factoryId: 'f3',
        featured: true,
    }
];

export const FACTORIES: F (Polished)actory[] = [
    {
        id: 'f1',
        name: 'Gouri Marble Udhyog',
        location: 'Kishangarh, Kali Dungri, Rajasthan - 305801',
        coordinates: { lat: 26.5741, lng: 74.8601 },
        capacity: '80,000 sq.ft / month',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790198/factory1_uzv7wd.jpg',
        altText: 'Gouri Marble Udhyog manufacturing facility in Kishangarh, Rajasthan',
        yearEstablished: 2000,
        specialization: 'Marble',
        machinery: ['CNC Cutting Machines', 'Polishing Units', 'Calibrating Lines', 'Bundling Equipment'],
        certifications: ['Export House Certificate', 'Eco-Friendly Operations', 'Govt. Recognized']
    },
    {
        id: 'f2',
        name: 'Gouri Granites',
        location: 'Kishangarh, Ralawta, Rajasthan - 305801',
        coordinates: { lat: 26.5850, lng: 74.8720 },
        capacity: '95,000 sq.ft / month',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790198/factory2_gihyqc.jpg',
        altText: 'Gouri Granites state-of-the-art facility for granite processing',
        yearEstablished: 2005,
        specialization: 'Granite & Quartz',
        machinery: ['Multi-Saw Cutting Lines', 'High-Precision Edge Profilers', 'Waterjet Cutting', 'Flaming Equipment'],
        certifications: ['Export House Certificate', 'Bureau of Indian Standards', 'Govt. Recognized']
    },
    {
        id: 'f3',
        name: 'Gouri Granito',
        location: 'Baopet, Karimnagar, Telangana - 505401',
        coordinates: { lat: 18.4386, lng: 78.4872 },
        capacity: '1,50,000 sq.ft / month',
        image: 'https://res.cloudinary.com/dvlapdn5x/image/upload/v1770790199/factory3_ulddda.jpg',
        altText: 'Gouri Granito advanced stone processing facility in Telangana',
        yearEstablished: 2010,
        specialization: 'Granite & Tiles',
        machinery: ['Large Format Saws', 'Grinding Machines', 'Tile Production Lines', 'Quality Control Systems'],
        certifications: ['Export House Certificate', 'Environmental Compliance', 'Govt. Recognized']
    }
];

export const CLIENT_LOCATIONS: ClientLocation[] = [
    { id: 'c1', country: 'United States', coordinates: { lat: 37.0902, lng: -95.7129 }, projectName: 'Luxury Hotel, NY' },
    { id: 'c2', country: 'UAE', coordinates: { lat: 23.4241, lng: 53.8478 }, projectName: 'Residential Tower, Dubai' },
    { id: 'c3', country: 'United Kingdom', coordinates: { lat: 55.3781, lng: -3.4360 }, projectName: 'Commercial Plaza, London' },
    { id: 'c4', country: 'Australia', coordinates: { lat: -25.2744, lng: 133.7751 }, projectName: 'Resort, Gold Coast' },
];

export const OWNERS: Owner[] = [
    {
        id: 'o1',
        name: 'Rajesh Gupta',
        role: 'Founder & CEO',
        bio: 'Over 30 years of experience in the natural stone industry, pioneering new extraction techniques.',
        image: 'https://placehold.co/300x300?text=RG'
    },
    {
        id: 'o2',
        name: 'Vikram Singh',
        role: 'Director of Exports',
        bio: 'Spearheading global expansion and ensuring international quality standards.',
        image: 'https://placehold.co/300x300?text=VS'
    }
];
