import { Product, Factory, Owner, ClientLocation } from './types';

export const PRODUCTS: Product[] = [
    {
        id: 'p1',
        name: 'Statuario Maximus',
        category: 'Marble',
        finish: 'Polished',
        dimensions: '3200 x 1600 mm',
        description: 'Premium white marble with bold grey veining, perfect for luxury interiors.',
        image: '/images/2.jpeg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p2',
        name: 'Black Galaxy',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Iconic deep black granite with gold speckles, durable and elegant.',
        image: '/images/3.jpeg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p3',
        name: 'Honey Onyx',
        category: 'Onyx',
        finish: 'Backlit',
        dimensions: '2400 x 1400 mm',
        description: 'Translucent stone with warm amber tones, ideal for statement features.',
        image: '/images/4.jpeg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p4',
        name: 'Silver Travertine',
        category: 'Travertine',
        finish: 'Honed',
        dimensions: '2800 x 1600 mm',
        description: 'Contemporary silver-grey travertine with linear veining.',
        image: '/images/5.jpeg',
        factoryId: 'f3',
        featured: true,
    },
    {
        id: 'p5',
        name: 'Colonial White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1900 mm',
        description: 'Soft white granite with speckles of black and dark red garnet.',
        image: '/images/media2/1.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p6',
        name: 'Viscon White',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '2900 x 1700 mm',
        description: 'A mesmerizing swirl of white, grey, and black waves.',
        image: '/images/media2/2.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p7',
        name: 'Tan Brown',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Classic dark brown granite with black and reddish-brown flecks.',
        image: '/images/media2/3.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p8',
        name: 'Absolute Black',
        category: 'Granite',
        finish: 'Honed',
        dimensions: '3200 x 1900 mm',
        description: 'The deepest, darkest black granite for a sleek modern look.',
        image: '/images/media2/4.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p9',
        name: 'Rainforest Green',
        category: 'Marble',
        finish: 'Polished',
        dimensions: '2800 x 1500 mm',
        description: 'Exotic green marble with intricate brown branching veins.',
        image: '/images/media2/5.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p10',
        name: 'Steel Grey',
        category: 'Granite',
        finish: 'Lappato',
        dimensions: '3000 x 1800 mm',
        description: 'Consistent low-variation grey granite, ideal for large commercial projects.',
        image: '/images/media2/6.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p11',
        name: 'Rajasthan Black',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '2900 x 1600 mm',
        description: 'Durable black granite with a textured finish for outdoor use.',
        image: '/images/media2/7.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p12',
        name: 'Kuppam Green',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2800 x 1700 mm',
        description: 'Vibrant green granite with flowing wavy patterns.',
        image: '/images/media2/8.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p13',
        name: 'Imperial Red',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3100 x 1800 mm',
        description: 'Deep red granite with blue-black accents, symbolizing royalty.',
        image: '/images/media2/9.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p14',
        name: 'Crystal Yellow',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1700 mm',
        description: 'Bright and cheerful yellow granite with uniform consistency.',
        image: '/images/media2/10.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p15',
        name: 'River White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Flowing rivers of white and light grey with red burgundy dots.',
        image: '/images/media2/11.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p16',
        name: 'Alaska White',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3200 x 1900 mm',
        description: 'Frosty mix of pale silver and frosty whites, marketed as exotic.',
        image: '/images/media2/12.jpg',
        factoryId: 'f2',
        featured: true,
    },
    {
        id: 'p17',
        name: 'Blue Dunes',
        category: 'Granite',
        finish: 'Leather',
        dimensions: '3100 x 1900 mm',
        description: 'Earth tones of varying cream, grey, and brown with unique blue hues.',
        image: '/images/media2/13.jpg',
        factoryId: 'f1',
        featured: true,
    },
    {
        id: 'p18',
        name: 'Monte Cristo',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1800 mm',
        description: 'Dynamic granite featuring sweeping waves of blue and grey.',
        image: '/images/media2/14.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p19',
        name: 'P White',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '2800 x 1600 mm',
        description: 'Economical and durable white granite, perfect for large scale paving.',
        image: '/images/media2/15.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p20',
        name: 'Tiger Skin',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1700 mm',
        description: 'Orange and black wavy patterns resembling a tiger\'s coat.',
        image: '/images/media2/16.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p21',
        name: 'Rosy Pink',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '3000 x 1700 mm',
        description: 'Pastel pink base with white and black flowers.',
        image: '/images/media2/17.jpg',
        factoryId: 'f2',
        featured: false,
    },
    {
        id: 'p22',
        name: 'Apple Green',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2800 x 1700 mm',
        description: 'Olive green background with speckles of pink and grey.',
        image: '/images/media2/18.jpg',
        factoryId: 'f3',
        featured: false,
    },
    {
        id: 'p23',
        name: 'Chima Pink',
        category: 'Granite',
        finish: 'Flamed',
        dimensions: '3100 x 1800 mm',
        description: 'Light pink granite widely used for flooring and cladding.',
        image: '/images/media2/19.jpg',
        factoryId: 'f1',
        featured: false,
    },
    {
        id: 'p24',
        name: 'Markino Red',
        category: 'Granite',
        finish: 'Polished',
        dimensions: '2900 x 1600 mm',
        description: 'Intense red background with bold black waves.',
        image: '/images/media2/20.jpg',
        factoryId: 'f2',
        featured: true,
    }
];

export const FACTORIES: Factory[] = [
    {
        id: 'f1',
        name: 'Gouri Marble Udhyog',
        location: 'Kishangarh, Kali Dungri, Rajasthan - 305801',
        coordinates: { lat: 26.5741, lng: 74.8601 },
        capacity: '80,000 sq.ft / month',
        image: '/images/factory1.jpeg'
    },
    {
        id: 'f2',
        name: 'Gouri Granites',
        location: 'Kishangarh, Ralawta, Rajasthan - 305801',
        coordinates: { lat: 26.5850, lng: 74.8720 },
        capacity: '95,000 sq.ft / month',
        image: '/images/factory2.jpeg'
    },
    {
        id: 'f3',
        name: 'Gouri Granito',
        location: 'Baopet, Karimnagar, Telangana - 505401',
        coordinates: { lat: 18.4386, lng: 78.4872 },
        capacity: '90,000 sq.ft / month',
        image: '/images/factory3.jpeg'
    }
];

export const CLIENT_LOCATIONS: ClientLocation[] = [
    { id: 'c1', country: 'United States', coordinates: { lat: 37.0902, lng: -95.7129 }, projectName: 'Luxury Hotel, NY' },
    { id: 'c2', country: 'UAE', coordinates: { lat: 23.4241, lng: 53.8478 }, projectName: 'Residential Tower, Dubai' },
    { id: 'c3', country: 'United Kingdom', coordinates: { lat: 55.3781, lng: -3.4360 }, projectName: 'Commercial Plaza, London' },
    { id: 'c4', country: 'Australia', coordinates: { lat: -25.2744, lng: 133.7751 }, projectName: 'Resort, Gold Coast' },
];

export const OWNERS: Owner[] = [
    {
        id: 'o1',
        name: 'Rajesh Gupta',
        role: 'Founder & CEO',
        bio: 'Over 30 years of experience in the natural stone industry, pioneering new extraction techniques.',
        image: 'https://placehold.co/300x300?text=RG'
    },
    {
        id: 'o2',
        name: 'Vikram Singh',
        role: 'Director of Exports',
        bio: 'Spearheading global expansion and ensuring international quality standards.',
        image: 'https://placehold.co/300x300?text=VS'
    }
];
